In [1]:
# importing all necessary libraries

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

import warnings
warnings.filterwarnings('ignore')

In [2]:
# reading in the dataset

df = pd.read_csv(r'C:\Users\seunt\Downloads\SUPERVISE ML UDEMY\datasets\HousePrice.csv')

df.head()

Area  Price
0  2422  32500
1  2130  27000
2  1900  24000
3  3100  44000
4  2700  36000

In [3]:
# separating the dependent variable 'Price' from the independent variable

x = df.iloc[: , 0:-1].values
y = df.iloc[: , -1].values

In [4]:
x

array([[2422],
       [2130],
       [1900],
       [3100],
       [2700],
       [2900],
       [3200],
       [2800],
       [3000],
       [3300],
       [3150],
       [2325],
       [2250],
       [3330],
       [2850],
       [3100],
       [2250],
       [2400],
       [2500]], dtype=int64)

In [5]:
# splitting into training and testing set

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [6]:
# creating and instance for the random forest regressor, fitting it to the training set and then making prediction

rf = RandomForestRegressor(n_estimators = 10)

rf.fit(X_train, Y_train)

y_pred = rf.predict(X_test)

In [7]:
X_test

array([[3150],
       [2130],
       [3000],
       [2500],
       [2850],
       [2250]], dtype=int64)

In [8]:
Y_test

array([43000, 27000, 41500, 35850, 41000, 30390], dtype=int64)

In [9]:
y_pred

array([44564.        , 30245.        , 42866.66666667, 31970.        ,
       39500.        , 30245.        ])

In [10]:
r_squared = r2_score(Y_test, y_pred)

r_squared

0.8507177772965393

In [11]:
# now let's see the performance of the random forest regressor when we have multiple independent variables

df2 = pd.read_csv(r'C:\Users\seunt\Downloads\SUPERVISE ML UDEMY\datasets\HousePrice2.csv')

df2.head()

Area  No of Rooms  Age of House  Price 
0  2422            4            35   32500
1  2130            3            39   27000
2  1900            2            16   24000
3  3100            6            41   44000
4  2700            4            36   36000

In [12]:
# separating the target variable from the independent variables

x1 = df2.iloc[: , :-1]

y1 = df2.iloc[: , -1]

In [13]:
x1.head()

Area  No of Rooms  Age of House
0  2422            4            35
1  2130            3            39
2  1900            2            16
3  3100            6            41
4  2700            4            36

In [14]:
y1.head()

0    32500
1    27000
2    24000
3    44000
4    36000
Name: Price , dtype: int64

In [15]:
# splitting into training and testing set

X_train, X_test, Y_train, Y_test = train_test_split(x1, y1, test_size = 0.3, random_state = 0)

In [16]:
# creating and instance for the random forest regressor, fitting it to the training set and then making prediction

rf = RandomForestRegressor(n_estimators = 10)

rf.fit(X_train, Y_train)

y_pred = rf.predict(X_test)

In [17]:
X_test

Area  No of Rooms  Age of House
1   2130            3            39
6   3200            7            24
8   3000            5            40
9   3300            6            29
14  2850            3            31

In [18]:
Y_train

4     36000
2     24000
13    49900
10    49000
7     28000
11    29000
3     44000
0     32500
5     42000
12    29910
Name: Price , dtype: int64

In [19]:
y_pred

array([29978., 48770., 39150., 48630., 33750.])

In [20]:
r_squared1 = r2_score(Y_test, y_pred)

r_squared1

0.8726595099384351

- The value of the R-Squared increased when will have multiple independent variables predicting the price of the house using the random forest regressor. It implies that these variables correlate to the price of the house thereby increasing the performance of the model.